/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.User;

import Model.Enterprise.bill.Bill;
import Model.Enterprise.bill.BillDirectory;
import Model.Role.User;
import java.awt.CardLayout;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tawde
 */
public class UserPayBill extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private List<Bill> userBills; 
    private BillDirectory billDirectory; 
    private User user; 

    /**
     * Creates new form UserPayBill
     */
    public UserPayBill(JPanel userProcessContainer, List<Bill> userBills, BillDirectory billDirectory, User user) {
        this.userProcessContainer = userProcessContainer;
        this.userBills = userBills;
        this.billDirectory = billDirectory;
        this.user = user;

        initComponents();
        populateTable();
    }

    /**
     * Populates the table with bills for the logged-in user
     */
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblBills.getModel();
        model.setRowCount(0);

        for (Bill bill : userBills) {
            Object[] row = new Object[3];
            row[0] = bill.getBillId();
            row[1] = "$" + bill.getAmount();
            row[2] = bill.isIsPaid() ? "Paid" : "Unpaid";
            model.addRow(row);
        }
    }

    private void generateBillReceipt(Bill bill) {
        String fileName = "BillReceipt_" + bill.getBillId() + ".txt";
        try (FileWriter writer = new FileWriter(fileName)) {
            writer.write("----- Bill Payment Receipt -----\n");
            writer.write("Bill ID: " + bill.getBillId() + "\n");
            writer.write("Amount Paid: $" + bill.getAmount() + "\n");
            writer.write("Payment Status: Paid\n");
            writer.write("Due Date: " + bill.getDueDate() + "\n");
            writer.write("-------------------------------\n");
            writer.write("Thank you for your payment!");
            writer.flush();

            javax.swing.JOptionPane.showMessageDialog(this, "Receipt downloaded: " + fileName, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to generate receipt.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnPayBillSubmit = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBills = new javax.swing.JTable();

        setBackground(new java.awt.Color(54, 116, 99));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pay Bill");

        btnPayBillSubmit.setBackground(new java.awt.Color(181, 143, 120));
        btnPayBillSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPayBillSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnPayBillSubmit.setText("Submit");
        btnPayBillSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillSubmitActionPerformed(evt);
            }
        });

        btnback1.setBackground(new java.awt.Color(181, 143, 120));
        btnback1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("<<Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        tblBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bill id", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblBills);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPayBillSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnback1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnPayBillSubmit)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayBillSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBills.getSelectedRow();
        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a bill to pay.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String billId = (String) tblBills.getValueAt(selectedRow, 0);
        Bill selectedBill = null;

        for (Bill bill : userBills) {
            if (bill.getBillId().equals(billId)) {
                selectedBill = bill;
                break;
            }
        }

        if (selectedBill != null && !selectedBill.isIsPaid()) {
            selectedBill.setIsPaid(true);
            javax.swing.JOptionPane.showMessageDialog(this, "Bill paid successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            generateBillReceipt(selectedBill);
            populateTable(); // Refresh the table
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "This bill is already paid.", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnPayBillSubmitActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnback1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayBillSubmit;
    private javax.swing.JButton btnback1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBills;
    // End of variables declaration//GEN-END:variables
}
