/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Model.Admin.Admin;
import Model.Admin.AdminDirectory;
import UI.Admin.CreateDriver;
import java.awt.CardLayout;
import Model.Business.Business;
import Model.Driver.DriverDirectory;
import Model.Supervisor.SupervisorDirectory;
import Model.Truck.TruckDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class AdminHome extends javax.swing.JPanel {
    Business business;
    DriverDirectory driverDirectory;
    JPanel userProcessContainer;
    SupervisorDirectory supervisorDirectory;
    TruckDirectory truckDirectory;

    /**
     * Creates new form AdminHome
     */
    public AdminHome(JPanel userProcessContainer, Business business, Admin authenticatedAdmin, AdminDirectory adminDirectory) {
        initComponents();
        driverDirectory = business.getDriverDirectory();
        supervisorDirectory = business.getSupervisorDirectory();
        truckDirectory = business.getTruckDirectory();
//        userProcessContainer = upc;
//        business = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateDriver = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblCreateTruck = new javax.swing.JLabel();
        btnDriverClick = new javax.swing.JButton();
        btnSupervisorClick = new javax.swing.JButton();
        lblCreateSupervisor = new javax.swing.JLabel();
        btnTruckClick = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        lblCreateDriver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateDriver.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateDriver.setText("Create Driver");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Admin Home Page");

        lblCreateTruck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateTruck.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateTruck.setText("Create Truck");

        btnDriverClick.setBackground(new java.awt.Color(181, 143, 120));
        btnDriverClick.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDriverClick.setForeground(new java.awt.Color(255, 255, 255));
        btnDriverClick.setText("Click Here");
        btnDriverClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverClickActionPerformed(evt);
            }
        });

        btnSupervisorClick.setBackground(new java.awt.Color(181, 143, 120));
        btnSupervisorClick.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSupervisorClick.setForeground(new java.awt.Color(255, 255, 255));
        btnSupervisorClick.setText("Click Here");
        btnSupervisorClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupervisorClickActionPerformed(evt);
            }
        });

        lblCreateSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateSupervisor.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateSupervisor.setText("Create Supervisor");

        btnTruckClick.setBackground(new java.awt.Color(181, 143, 120));
        btnTruckClick.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTruckClick.setForeground(new java.awt.Color(255, 255, 255));
        btnTruckClick.setText("Click Here");
        btnTruckClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruckClickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateDriver)
                    .addComponent(lblCreateTruck)
                    .addComponent(lblCreateSupervisor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDriverClick, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTruckClick, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupervisorClick, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDriverClick)
                    .addComponent(lblCreateDriver))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTruckClick)
                    .addComponent(lblCreateTruck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupervisorClick)
                    .addComponent(lblCreateSupervisor))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDriverClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverClickActionPerformed
        // TODO add your handling code here:
        CreateDriver CD = new CreateDriver(userProcessContainer,business ,driverDirectory);
        userProcessContainer.add("CreateDriver", CD);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDriverClickActionPerformed

    private void btnSupervisorClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupervisorClickActionPerformed
        // TODO add your handling code here:
        CreateSupervisor CS = new CreateSupervisor(userProcessContainer,business ,supervisorDirectory);
        userProcessContainer.add("CreateSupervisor", CS);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSupervisorClickActionPerformed

    private void btnTruckClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruckClickActionPerformed
        CreateTruck CT = new CreateTruck(userProcessContainer,business ,truckDirectory);
        userProcessContainer.add("CreateTruck", CT);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTruckClickActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDriverClick;
    private javax.swing.JButton btnSupervisorClick;
    private javax.swing.JButton btnTruckClick;
    private javax.swing.JLabel lblCreateDriver;
    private javax.swing.JLabel lblCreateSupervisor;
    private javax.swing.JLabel lblCreateTruck;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
