/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author tawde
 */
public class AdminLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminLoginJPanel
     */
    public AdminLoginJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminLogin = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAdminPassword = new javax.swing.JLabel();
        btnAdminSubmit = new javax.swing.JButton();
        jTextFieldAdminPassword = new javax.swing.JTextField();
        jTextFieldAdminID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(54, 116, 99));

        lblAdminLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminLogin.setText("Admin ID");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Admin Login");

        lblAdminPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAdminPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminPassword.setText("Password");

        btnAdminSubmit.setBackground(new java.awt.Color(181, 143, 120));
        btnAdminSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminSubmit.setText("Submit");
        btnAdminSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSubmitActionPerformed(evt);
            }
        });

        jTextFieldAdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdminPasswordActionPerformed(evt);
            }
        });

        jTextFieldAdminID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdminIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAdminLogin)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdminPassword)
                        .addGap(51, 51, 51)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldAdminID, jTextFieldAdminPassword});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminLogin)
                    .addComponent(jTextFieldAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminPassword)
                    .addComponent(jTextFieldAdminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnAdminSubmit)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminSubmitActionPerformed

    private void jTextFieldAdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdminPasswordActionPerformed

    private void jTextFieldAdminIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdminIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdminIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminSubmit;
    private javax.swing.JTextField jTextFieldAdminID;
    private javax.swing.JTextField jTextFieldAdminPassword;
    private javax.swing.JLabel lblAdminLogin;
    private javax.swing.JLabel lblAdminPassword;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
