/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business.Business;
import Model.Supervisor.Supervisor;
import Model.Supervisor.SupervisorDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author tawde
 */
public class SupervisorLoginJPanel extends javax.swing.JPanel {
    
    Business  business;
    SupervisorDirectory supervisorDirectory;

    /**
     * Creates new form SupervisorLoginJPanel
     */
    public SupervisorLoginJPanel() {
        initComponents();
        business = new Business();
        supervisorDirectory = business.getSupervisorDirectory();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSupervisorPassword = new javax.swing.JTextField();
        jTextFieldSupervisorID = new javax.swing.JTextField();
        lblSupervisorLogin = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSupervisorPassword = new javax.swing.JLabel();
        btnSupervisorSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        jTextFieldSupervisorPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorPasswordActionPerformed(evt);
            }
        });

        jTextFieldSupervisorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorIDActionPerformed(evt);
            }
        });

        lblSupervisorLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSupervisorLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblSupervisorLogin.setText("Supervisor ID");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Supervisor Login");

        lblSupervisorPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSupervisorPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblSupervisorPassword.setText("Password");

        btnSupervisorSubmit.setBackground(new java.awt.Color(181, 143, 120));
        btnSupervisorSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSupervisorSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSupervisorSubmit.setText("Submit");
        btnSupervisorSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupervisorSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSupervisorSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSupervisorLogin)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSupervisorPassword)
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSupervisorID)
                            .addComponent(jTextFieldSupervisorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupervisorLogin)
                    .addComponent(jTextFieldSupervisorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupervisorPassword)
                    .addComponent(jTextFieldSupervisorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnSupervisorSubmit)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSupervisorPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorPasswordActionPerformed

    private void jTextFieldSupervisorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorIDActionPerformed

    private void btnSupervisorSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupervisorSubmitActionPerformed
        // TODO add your handling code here:
        
        String supervisorId = jTextFieldSupervisorID.getText().trim();
        String password = jTextFieldSupervisorPassword.getText().trim();
    
    // Assuming supervisorDirectory is accessible here, e.g., passed via constructor
    Supervisor validSupervisor = supervisorDirectory.authenticateSupervisor(supervisorId, password);
    
    if (validSupervisor != null) {
        JOptionPane.showMessageDialog(this, "Login successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        // Proceed to next panel or operation post successful login
    } else {
        JOptionPane.showMessageDialog(this, "Invalid ID or Password", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSupervisorSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSupervisorSubmit;
    private javax.swing.JTextField jTextFieldSupervisorID;
    private javax.swing.JTextField jTextFieldSupervisorPassword;
    private javax.swing.JLabel lblSupervisorLogin;
    private javax.swing.JLabel lblSupervisorPassword;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
