/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Business.Business;
import Model.Complaint.ComplaintDirectory;
import Model.Role.Supervisor;
import Model.Role.SupervisorDirectory;
import Model.Role.UserDirectory;
import UI.Dashboard.SupervisorDashboard;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class SupervisorLoginJPanel extends javax.swing.JPanel {
    
    Business  business;
    private SupervisorDirectory supervisorDirectory;
    private JPanel userProcessContainer;
    private ComplaintDirectory complaintdirectory;

    /**
     * Creates new form SupervisorLoginJPanel
     */
    public SupervisorLoginJPanel(JPanel userProcessContainer,Business business ,SupervisorDirectory supervisorDirectory,ComplaintDirectory complaintdirectory, UserDirectory userDirectory) {
        initComponents();
        this.business = business;
        this.userProcessContainer=userProcessContainer;
        this.supervisorDirectory = supervisorDirectory;
        this.complaintdirectory=complaintdirectory;
        supervisorDirectory = business.getSupervisorDirectory();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSuppass = new javax.swing.JTextField();
        txtSupid = new javax.swing.JTextField();
        lblSupervisorLogin = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSupervisorPassword = new javax.swing.JLabel();
        btnSupervisorSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        txtSuppass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuppassActionPerformed(evt);
            }
        });

        txtSupid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupidActionPerformed(evt);
            }
        });

        lblSupervisorLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSupervisorLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblSupervisorLogin.setText("Supervisor ID");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Supervisor Login");

        lblSupervisorPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSupervisorPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblSupervisorPassword.setText("Password");

        btnSupervisorSubmit.setBackground(new java.awt.Color(181, 143, 120));
        btnSupervisorSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSupervisorSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSupervisorSubmit.setText("Submit");
        btnSupervisorSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupervisorSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSupervisorSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSupervisorLogin)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSupervisorPassword)
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSupid)
                            .addComponent(txtSuppass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupervisorLogin)
                    .addComponent(txtSupid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupervisorPassword)
                    .addComponent(txtSuppass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnSupervisorSubmit)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSuppassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuppassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuppassActionPerformed

    private void txtSupidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupidActionPerformed

    private void btnSupervisorSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupervisorSubmitActionPerformed
        // TODO add your handling code here:
        // Retrieve the user input
    String supervisorId = txtSupid.getText().trim();
    String password = txtSuppass.getText().trim();

    // Check if the credentials are correct
    if (supervisorDirectory != null) {
        Supervisor authenticatedSupervisor = supervisorDirectory.authenticateSupervisor(supervisorId, password);
        if (authenticatedSupervisor != null) {
            // Login successful
            JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Assuming you have access to userProcessContainer from here, otherwise you need to pass it or get it from the parent JFrame
            SupervisorDashboard dashboard = new SupervisorDashboard(userProcessContainer,business ,authenticatedSupervisor, supervisorDirectory,complaintdirectory);
            userProcessContainer.add("SupervisorDashboard", dashboard);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            // Login failed
            JOptionPane.showMessageDialog(this, "Invalid supervisor ID or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // If supervisorDirectory is not initialized
        JOptionPane.showMessageDialog(this, "Login system not available.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSupervisorSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSupervisorSubmit;
    private javax.swing.JLabel lblSupervisorLogin;
    private javax.swing.JLabel lblSupervisorPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtSupid;
    private javax.swing.JTextField txtSuppass;
    // End of variables declaration//GEN-END:variables
}
