/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Admin.Admin;
import Model.Admin.AdminDirectory;
import Model.Business.Business;
import Model.Complaint.ComplaintDirectory;
import Model.Role.SupervisorDirectory;
import Model.Role.User;
import Model.Role.UserDirectory;
import UI.Dashboard.SupervisorDashboard;
import UI.Dashboard.UserDashboard;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class UserLoginJPanel extends javax.swing.JPanel {

    Business business;
    private SupervisorDirectory supervisorDirectory;
    private ComplaintDirectory complaintDirectory;
    private UserDirectory userDirectory;
    JPanel userProcessContainer;
    
    /**
     * Creates new form UserLoginJPanel
     */
    public UserLoginJPanel(JPanel userProcessContainer,Business business ,SupervisorDirectory supervisorDirectory,ComplaintDirectory complaintDirectory, UserDirectory userDirectory) {
        initComponents();
        this.business = business;
        this.userProcessContainer=userProcessContainer;
        this.supervisorDirectory = supervisorDirectory;
        this.complaintDirectory=complaintDirectory;
        supervisorDirectory = business.getSupervisorDirectory();
        this.userDirectory = userDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserPass = new javax.swing.JTextField();
        txtUserId = new javax.swing.JTextField();
        lblUserLogin = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUserPassword = new javax.swing.JLabel();
        btnUserSubmit = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        txtUserPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPassActionPerformed(evt);
            }
        });

        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        lblUserLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblUserLogin.setText("User ID");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("User Login");

        lblUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUserPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblUserPassword.setText("Password");

        btnUserSubmit.setBackground(new java.awt.Color(181, 143, 120));
        btnUserSubmit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUserSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnUserSubmit.setText("Submit");
        btnUserSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserPassword)
                    .addComponent(lblUserLogin))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserId, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtUserPass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUserSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserLogin)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPassword)
                    .addComponent(txtUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnUserSubmit)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPassActionPerformed

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void btnUserSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSubmitActionPerformed
        // TODO add your handling code here:
        if (userDirectory == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "User directory not initialized", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
        }
        String userId = txtUserId.getText().trim();  // Assume txtUserId and txtUserPass are the input fields for user credentials
        String password = txtUserPass.getText().trim();
        
        if (userId.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter both User ID and Password", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
        }
        User user = userDirectory.findUserById(userId);
        
        if (user != null && password.equals(user.getPassword())) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Login Successful", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        // Proceed to the next screen (userDashBoard)
            UserDashboard dashboard = new UserDashboard(userProcessContainer,business , supervisorDirectory,complaintDirectory);
            userProcessContainer.add("SupervisorDashboard", dashboard);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid User ID or Password", "Login Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnUserSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserSubmit;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserLogin;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserPass;
    // End of variables declaration//GEN-END:variables
}
