/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Dashboard;

/**
 *
 * @author tawde
 */
public class AdminDashboard extends javax.swing.JPanel {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCheckTruck = new javax.swing.JButton();
        btnCheckSupervisor = new javax.swing.JButton();
        btnCheckDriver = new javax.swing.JButton();
        btnCheckRoute = new javax.swing.JButton();
        btnCheckUser = new javax.swing.JButton();
        btnTotalTrash = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Admin Dashboard");

        btnCheckTruck.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckTruck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckTruck.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckTruck.setText("Check Truck");
        btnCheckTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckTruckActionPerformed(evt);
            }
        });

        btnCheckSupervisor.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckSupervisor.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckSupervisor.setText("Check Supervisor");
        btnCheckSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckSupervisorActionPerformed(evt);
            }
        });

        btnCheckDriver.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckDriver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckDriver.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckDriver.setText("Check Driver");
        btnCheckDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckDriverActionPerformed(evt);
            }
        });

        btnCheckRoute.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckRoute.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckRoute.setText("Check Route");
        btnCheckRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckRouteActionPerformed(evt);
            }
        });

        btnCheckUser.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckUser.setText("Check User ");
        btnCheckUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUserActionPerformed(evt);
            }
        });

        btnTotalTrash.setBackground(new java.awt.Color(181, 143, 120));
        btnTotalTrash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTotalTrash.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalTrash.setText("Total Trash");
        btnTotalTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalTrashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnTotalTrash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCheckUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckSupervisor))
                .addGap(17, 17, 17))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCheckDriver, btnCheckRoute, btnCheckSupervisor, btnCheckTruck, btnCheckUser});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(55, 55, 55)
                .addComponent(btnCheckTruck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckSupervisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnTotalTrash)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckTruckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckTruckActionPerformed

    private void btnCheckSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckSupervisorActionPerformed

    private void btnCheckDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckDriverActionPerformed

    }//GEN-LAST:event_btnCheckDriverActionPerformed

    private void btnCheckRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckRouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckRouteActionPerformed

    private void btnCheckUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckUserActionPerformed

    private void btnTotalTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalTrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalTrashActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckDriver;
    private javax.swing.JButton btnCheckRoute;
    private javax.swing.JButton btnCheckSupervisor;
    private javax.swing.JButton btnCheckTruck;
    private javax.swing.JButton btnCheckUser;
    private javax.swing.JButton btnTotalTrash;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
