/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Dashboard;

import Model.Business.Business;
import Model.Supervisor.Supervisor;
import Model.Supervisor.SupervisorDirectory;
import UI.Supervisor.SupervisorAssignDriver;
import UI.Supervisor.SupervisorAssignTruck;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author arslanparkar
 */
public class SupervisorDashboard extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Supervisor authenticatedSupervisor;
    private SupervisorDirectory supervisorDirectory;
    private Business business;

    /**
     * Creates new form SupervisorDashboard
     */
    public SupervisorDashboard(JPanel userProcessContainer, Business business, Supervisor authenticatedSupervisor, SupervisorDirectory supervisorDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.authenticatedSupervisor = authenticatedSupervisor;
        this.supervisorDirectory = supervisorDirectory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTotalTrash = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnAssignTruck = new javax.swing.JButton();
        btnAssignDriver = new javax.swing.JButton();
        btnAssignRoute = new javax.swing.JButton();
        btnCheckUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        btnTotalTrash.setBackground(new java.awt.Color(181, 143, 120));
        btnTotalTrash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTotalTrash.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalTrash.setText("Total Trash");
        btnTotalTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalTrashActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(" Supervisor Dashboard");

        btnAssignTruck.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignTruck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignTruck.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignTruck.setText("Assign Truck");
        btnAssignTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTruckActionPerformed(evt);
            }
        });

        btnAssignDriver.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignDriver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignDriver.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignDriver.setText("Assign Driver");
        btnAssignDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDriverActionPerformed(evt);
            }
        });

        btnAssignRoute.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignRoute.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRoute.setText("Assign Route ");
        btnAssignRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRouteActionPerformed(evt);
            }
        });

        btnCheckUser.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckUser.setText("Check User ");
        btnCheckUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnTotalTrash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCheckUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignRoute))
                .addGap(17, 17, 17))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAssignDriver, btnAssignRoute, btnAssignTruck, btnCheckUser});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(68, 68, 68)
                .addComponent(btnAssignTruck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAssignDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAssignRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnTotalTrash)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalTrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalTrashActionPerformed

    private void btnAssignTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTruckActionPerformed
        // TODO add your handling code here:
        SupervisorAssignTruck assignTruckPanel = new SupervisorAssignTruck(userProcessContainer, business, authenticatedSupervisor, supervisorDirectory);
        userProcessContainer.add("SupervisorAssignTruck", assignTruckPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignTruckActionPerformed

    private void btnAssignDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDriverActionPerformed
        SupervisorAssignDriver assignDriverPanel = new SupervisorAssignDriver(userProcessContainer, business, authenticatedSupervisor, supervisorDirectory);
        userProcessContainer.add("SupervisorAssignDriver", assignDriverPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignDriverActionPerformed

    private void btnAssignRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignRouteActionPerformed

    private void btnCheckUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignDriver;
    private javax.swing.JButton btnAssignRoute;
    private javax.swing.JButton btnAssignTruck;
    private javax.swing.JButton btnCheckUser;
    private javax.swing.JButton btnTotalTrash;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
