/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Dashboard;

import Model.Business.Business;
import Model.Driver.Driver;
import Model.Route.Route;
import Model.Supervisor.Supervisor;
import Model.Supervisor.SupervisorDirectory;
import Model.Truck.Truck;
import UI.Supervisor.SupervisorAssignRoute;
import UI.Supervisor.SupervisorCreateRoute;
import UI.Supervisor.SupervisorAssignTruck;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arslanparkar
 */
public class SupervisorDashboard extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Supervisor authenticatedSupervisor;
    private SupervisorDirectory supervisorDirectory;
    private Business business;

    /**
     * Creates new form SupervisorDashboard
     */
    public SupervisorDashboard(JPanel userProcessContainer, Business business, Supervisor authenticatedSupervisor, SupervisorDirectory supervisorDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.authenticatedSupervisor = authenticatedSupervisor;
        this.supervisorDirectory = supervisorDirectory;
        
        initComponents();
        populateDriverTruckTable();
        updateTableAfterAssignment();
    }

    public void updateTableAfterAssignment() {
    populateDriverTruckTable();  // This method refreshes the JTable
    System.out.println("Refreshing driver-truck table data...");
    }
    
    public void populateDriverTruckTable() {
    DefaultTableModel model = (DefaultTableModel) jTableSupreport.getModel();
    model.setRowCount(0); // Clear existing rows

    for (Driver driver : business.getDriverDirectory().getDrivers()) {
        Truck truck = driver.getAssignedTruck();
        Route route = truck != null ? truck.getAssignedRoute() : null;
        String routeDescription = route != null ? route.getRouteId() + " - From " + route.getStart() + " to " + route.getEnd() : "No route assigned";
        if (truck != null) { // Only display drivers with assigned trucks
            String truckDisplay = truck.getTruckId() + " - " + truck.getDescription();
            model.addRow(new Object[]{driver.getName(), truckDisplay, routeDescription});
        }
    }
    System.out.println("Table refreshed with current truck and route assignments.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTotalTrash = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnAssignTruck = new javax.swing.JButton();
        btnCreateRoute = new javax.swing.JButton();
        btnAssignRoute = new javax.swing.JButton();
        btnCheckUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSupreport = new javax.swing.JTable();

        setBackground(new java.awt.Color(54, 116, 99));

        btnTotalTrash.setBackground(new java.awt.Color(181, 143, 120));
        btnTotalTrash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTotalTrash.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalTrash.setText("Total Trash");
        btnTotalTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalTrashActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText(" Supervisor Dashboard");

        btnAssignTruck.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignTruck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignTruck.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignTruck.setText("Assign Truck");
        btnAssignTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTruckActionPerformed(evt);
            }
        });

        btnCreateRoute.setBackground(new java.awt.Color(181, 143, 120));
        btnCreateRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateRoute.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateRoute.setText("Create Route");
        btnCreateRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRouteActionPerformed(evt);
            }
        });

        btnAssignRoute.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignRoute.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignRoute.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRoute.setText("Assign Route ");
        btnAssignRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRouteActionPerformed(evt);
            }
        });

        btnCheckUser.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckUser.setText("Check User ");
        btnCheckUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUserActionPerformed(evt);
            }
        });

        jTableSupreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Driver", "Truck", "Route"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSupreport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTotalTrash)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCheckUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssignTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssignRoute))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAssignRoute, btnAssignTruck, btnCheckUser, btnCreateRoute});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAssignTruck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreateRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAssignRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCheckUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnTotalTrash)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalTrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalTrashActionPerformed

    private void btnAssignTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTruckActionPerformed
        // TODO add your handling code here:
        SupervisorAssignTruck assignTruckPanel = new SupervisorAssignTruck(userProcessContainer, business, authenticatedSupervisor, supervisorDirectory, this);
        userProcessContainer.add("SupervisorAssignTruck", assignTruckPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignTruckActionPerformed

    private void btnAssignRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRouteActionPerformed
        // TODO add your handling code here:
        SupervisorAssignRoute SAR = new SupervisorAssignRoute(userProcessContainer, business, authenticatedSupervisor, supervisorDirectory);
        userProcessContainer.add("SupervisorAssignRoute", SAR);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnAssignRouteActionPerformed

    private void btnCheckUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckUserActionPerformed

    private void btnCreateRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRouteActionPerformed
        SupervisorCreateRoute assignDriverPanel = new SupervisorCreateRoute(userProcessContainer, business, authenticatedSupervisor, supervisorDirectory);
        userProcessContainer.add("SupervisorAssignDriver", assignDriverPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateRouteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRoute;
    private javax.swing.JButton btnAssignTruck;
    private javax.swing.JButton btnCheckUser;
    private javax.swing.JButton btnCreateRoute;
    private javax.swing.JButton btnTotalTrash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSupreport;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
