/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Dashboard;

import Model.Business.Business;
import Model.Enterprise.Compliance.ComplaintDirectory;
import Model.Role.SupervisorDirectory;
import UI.Supervisor.SupervisorAssignTruck;
import UI.User.UserFileComplain;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class UserDashboard extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business ;
    private SupervisorDirectory supervisorDirectory;
    private ComplaintDirectory complaintDirectory;

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard(JPanel userProcessContainer,Business business ,SupervisorDirectory supervisorDirectory,ComplaintDirectory complaintDirectory) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        this.supervisorDirectory=supervisorDirectory;
        this.complaintDirectory=complaintDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTotalTrash = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnCheckBill = new javax.swing.JButton();
        btnPayBill = new javax.swing.JButton();
        btnComplain = new javax.swing.JButton();
        btnaddtrash = new javax.swing.JButton();
        btnAddRemove1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        btnTotalTrash.setBackground(new java.awt.Color(181, 143, 120));
        btnTotalTrash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTotalTrash.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalTrash.setText("Total Trash");
        btnTotalTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalTrashActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("User Dashboard");

        btnCheckBill.setBackground(new java.awt.Color(181, 143, 120));
        btnCheckBill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckBill.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckBill.setText("Check Bill");
        btnCheckBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBillActionPerformed(evt);
            }
        });

        btnPayBill.setBackground(new java.awt.Color(181, 143, 120));
        btnPayBill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPayBill.setForeground(new java.awt.Color(255, 255, 255));
        btnPayBill.setText("Pay Bill");
        btnPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillActionPerformed(evt);
            }
        });

        btnComplain.setBackground(new java.awt.Color(181, 143, 120));
        btnComplain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnComplain.setForeground(new java.awt.Color(255, 255, 255));
        btnComplain.setText("Complaint");
        btnComplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplainActionPerformed(evt);
            }
        });

        btnaddtrash.setBackground(new java.awt.Color(181, 143, 120));
        btnaddtrash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnaddtrash.setForeground(new java.awt.Color(255, 255, 255));
        btnaddtrash.setText("add trash");
        btnaddtrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtrashActionPerformed(evt);
            }
        });

        btnAddRemove1.setBackground(new java.awt.Color(181, 143, 120));
        btnAddRemove1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddRemove1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRemove1.setText("Add/Remove");
        btnAddRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRemove1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnTotalTrash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPayBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(btnCheckBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(btnComplain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(btnaddtrash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRemove1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(67, 67, 67)
                .addComponent(btnCheckBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPayBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComplain)
                .addGap(18, 18, 18)
                .addComponent(btnAddRemove1)
                .addGap(13, 13, 13)
                .addComponent(btnaddtrash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnTotalTrash)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalTrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTotalTrashActionPerformed

    private void btnCheckBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckBillActionPerformed

    private void btnPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillActionPerformed

    }//GEN-LAST:event_btnPayBillActionPerformed

    private void btnComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplainActionPerformed
        // TODO add your handling code here:
        UserFileComplain ufc = new UserFileComplain(complaintDirectory, userProcessContainer);
        userProcessContainer.add("UserFileComplain", ufc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnComplainActionPerformed

    private void btnaddtrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddtrashActionPerformed

    private void btnAddRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRemove1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRemove1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRemove1;
    private javax.swing.JButton btnCheckBill;
    private javax.swing.JButton btnComplain;
    private javax.swing.JButton btnPayBill;
    private javax.swing.JButton btnTotalTrash;
    private javax.swing.JButton btnaddtrash;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
