/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Driver;

import Model.Business.Business;
import Model.Role.Driver;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Arslan
 */
public class DriverPickUpRegister extends javax.swing.JPanel {

 private JPanel userProcessContainer;
    private Business business;
    private Driver driver;
    /**
     * Creates new form DriverPickUpRegister
     */
    public DriverPickUpRegister(JPanel userProcessContainer, Business business, Driver driver) {
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.driver = driver;
        initComponents();
        populateComboBoxes();
    }
    
    private void populateComboBoxes() {
        // This should populate combo boxes from the business model
        comboRoute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Route 101", "Route 102", "Route 103" }));
        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User 1", "User 2", "User 3" }));
        combostatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed", "Delayed" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboRoute = new javax.swing.JComboBox<>();
        comboUser = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();
        btnAssignRouteSet = new javax.swing.JButton();
        lblChooseTrashid = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblRouteNo = new javax.swing.JLabel();
        combostatus = new javax.swing.JComboBox<>();
        lblstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(54, 116, 99));

        comboRoute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnback.setBackground(new java.awt.Color(181, 143, 120));
        btnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnAssignRouteSet.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignRouteSet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAssignRouteSet.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRouteSet.setText("Set");
        btnAssignRouteSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRouteSetActionPerformed(evt);
            }
        });

        lblChooseTrashid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseTrashid.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseTrashid.setText("User");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pickup Trash");

        lblRouteNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRouteNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRouteNo.setText("Route No");

        combostatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblstatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(255, 255, 255));
        lblstatus.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignRouteSet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRouteNo)
                    .addComponent(lblChooseTrashid)
                    .addComponent(lblstatus))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combostatus, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnback))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChooseTrashid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRouteNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblstatus)
                    .addComponent(combostatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnAssignRouteSet)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnbackActionPerformed

    private void btnAssignRouteSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRouteSetActionPerformed
        // TODO add your handling code here:
        
        String selectedUser = (String) comboUser.getSelectedItem();
        String selectedRoute = (String) comboRoute.getSelectedItem();
        String selectedStatus = (String) combostatus.getSelectedItem();
        if (selectedUser != null && selectedRoute != null && selectedStatus != null) {
            // Implement logic based on your model's methods to set route and status for the user
            JOptionPane.showMessageDialog(null, "Route assigned to user successfully with status: " + selectedStatus, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Please select all fields correctly.", "Error", JOptionPane.ERROR_MESSAGE);
        }

       
    }//GEN-LAST:event_btnAssignRouteSetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRouteSet;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> comboRoute;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JComboBox<String> combostatus;
    private javax.swing.JLabel lblChooseTrashid;
    private javax.swing.JLabel lblRouteNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblstatus;
    // End of variables declaration//GEN-END:variables
}
