/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Driver;

import Model.Business.Business;
import Model.Enterprise.Compliance.Complaint;
import Model.Enterprise.Compliance.ComplaintDirectory;
import Model.Enterprise.Logistic.Route;
import Model.Enterprise.bill.Bill;
import Model.Enterprise.bill.BillDirectory;
import Model.Role.Driver;
import Model.Role.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class DriverPickUpComplain extends javax.swing.JPanel {
     private ComplaintDirectory complaintDirectory;
    private JPanel userProcessContainer;
    private Business business;
    private Driver driver;

    /**
     * Creates new form DriverPickUpComplain
     */
    public DriverPickUpComplain(JPanel userProcessContainer, Business business, Driver driver, ComplaintDirectory complaintDirectory, DriverDashboard driverDashboard) {
    if (complaintDirectory == null) {
        throw new IllegalArgumentException("ComplaintDirectory cannot be null");
    }
    this.userProcessContainer = userProcessContainer;
    this.business = business;
    this.driver = driver;
    this.complaintDirectory = complaintDirectory;
    initComponents();
    populateComboBoxes();
}
    
    private void populateComboBoxes() {
        // Populate users and routes from the business model
        comboUser.removeAllItems();
        comboRoute.removeAllItems();

        for (User user : business.getUserDirectory().getUsers()) {
            comboUser.addItem(user.getId() + " - " + user.getName());
        }

        for (Route route : business.getRouteDirectory().getRoutes()) {
            comboRoute.addItem(route.getRouteId() + " - " + route.getDescription());
        }

        // Populate complaint types
        combocomplain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bin Filled", "Trash Overflow", "Delayed Pickup" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Compplian = new javax.swing.JLabel();
        comboRoute = new javax.swing.JComboBox<>();
        comboUser = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();
        btnAssignRouteSet = new javax.swing.JButton();
        lblChooseuser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblRouteNo = new javax.swing.JLabel();
        combocomplain = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(54, 116, 99));

        Compplian.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Compplian.setForeground(new java.awt.Color(255, 255, 255));
        Compplian.setText("Status");

        comboRoute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnback.setBackground(new java.awt.Color(181, 143, 120));
        btnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnAssignRouteSet.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignRouteSet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAssignRouteSet.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRouteSet.setText("Set");
        btnAssignRouteSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRouteSetActionPerformed(evt);
            }
        });

        lblChooseuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseuser.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseuser.setText("USER");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Pickup Complain");

        lblRouteNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRouteNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRouteNo.setText("Route No");

        combocomplain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssignRouteSet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRouteNo)
                            .addComponent(lblChooseuser)
                            .addComponent(Compplian))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combocomplain, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnback))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChooseuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRouteNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Compplian)
                    .addComponent(combocomplain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnAssignRouteSet)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnAssignRouteSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRouteSetActionPerformed
        // TODO add your handling code here:
    try {
        String selectedUser = (String) comboUser.getSelectedItem();
        String selectedRoute = (String) comboRoute.getSelectedItem();
        String complaintType = (String) combocomplain.getSelectedItem();

        if (selectedUser == null || selectedRoute == null || complaintType == null) {
            JOptionPane.showMessageDialog(null, "Please select all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String userId = selectedUser.split(" - ")[0];
        String routeId = selectedRoute.split(" - ")[0];

        User user = business.getUserDirectory().findUserById(userId);
        Route route = business.getRouteDirectory().findRouteById(routeId);

        if (user == null || route == null) {
            JOptionPane.showMessageDialog(null, "User or Route not found. Please check the selections.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Log complaint
        Complaint complaint = new Complaint("C" + System.currentTimeMillis(), "Complaint about " + complaintType, false);
        complaintDirectory.addComplaint(complaint);
        route.setStatus("Complaint logged");

        // Handle trash overflow and generate a bill
        if ("Trash Overflow".equals(complaintType)) {
            // Ensure BillDirectory exists
            if (business.getBillDirectory() == null) {
                business.setBillDirectory(new BillDirectory());
            }

            // Generate a bill
            Bill bill = new Bill();
            bill.setBillId("B" + System.currentTimeMillis());
            bill.setAmount(150.0); // Example fixed amount for overflow
            bill.setIsPaid(false);
            bill.setDueDate("2024-12-31");
            business.getBillDirectory().addBill(userId, bill);

            JOptionPane.showMessageDialog(null, "Bill generated for Trash Overflow. Amount: $150", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

        JOptionPane.showMessageDialog(null, "Complaint logged successfully for " + user.getName(), "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAssignRouteSetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Compplian;
    private javax.swing.JButton btnAssignRouteSet;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> comboRoute;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JComboBox<String> combocomplain;
    private javax.swing.JLabel lblChooseuser;
    private javax.swing.JLabel lblRouteNo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
