/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Supervisor;

import Model.Business.Business;
import Model.Enterprise.Logistic.Route;
import Model.Enterprise.Logistic.RouteDirectory;
import Model.Role.Supervisor;
import Model.Role.SupervisorDirectory;
import Model.Enterprise.Vehicle.Truck;
import Model.Role.User;
import Model.Role.UserDirectory;
import UI.Dashboard.SupervisorDashboard;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class SupervisorAssignUser extends javax.swing.JPanel {

    private Business business;
    private JPanel userProcessContainer;
    private Supervisor authenticatedSupervisor;
    private SupervisorDirectory supervisorDirectory;
    private SupervisorDashboard dashboard;
    private UserDirectory userDirectory;
    private RouteDirectory routeDirectory;
    /**
     * Creates new form SupervisorAssignRoute
     */
    public SupervisorAssignUser(JPanel userProcessContainer, Business business, Supervisor authenticatedSupervisor, SupervisorDirectory supervisorDirectory) {
     this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.authenticatedSupervisor = authenticatedSupervisor;
        this.supervisorDirectory = supervisorDirectory;
        this.userDirectory = business.getUserDirectory(); // Assuming UserDirectory is part of Business
        this.routeDirectory = business.getRouteDirectory(); // Assuming RouteDirectory is part of Business
        initComponents();
        populateComboBoxes();
}
    
    private void populateComboBoxes() {
    comboUser.removeAllItems();
    comboRoute.removeAllItems();

    for (User user : business.getUserDirectory().getUsers()) {
        comboUser.addItem(user.getId() + " - " + user.getName());
    }
    for (Route route : business.getRouteDirectory().getRoutes()) {
        comboRoute.addItem(route.getRouteId() + " - " + route.getDescription());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssignRouteSet = new javax.swing.JButton();
        lblChooseUser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblRouteNo = new javax.swing.JLabel();
        comboRoute = new javax.swing.JComboBox<>();
        comboUser = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        btnAssignRouteSet.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignRouteSet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAssignRouteSet.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRouteSet.setText("Set");
        btnAssignRouteSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRouteSetActionPerformed(evt);
            }
        });

        lblChooseUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseUser.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseUser.setText("User");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Assign Route");

        lblRouteNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRouteNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRouteNo.setText("Route No");

        comboRoute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnback.setBackground(new java.awt.Color(181, 143, 120));
        btnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRouteNo)
                    .addComponent(lblChooseUser))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignRouteSet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnback))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChooseUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRouteNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addComponent(btnAssignRouteSet)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignRouteSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRouteSetActionPerformed
    String selectedUser = (String) comboUser.getSelectedItem();
    String selectedRoute = (String) comboRoute.getSelectedItem();

    if (selectedUser == null || selectedRoute == null) {
        JOptionPane.showMessageDialog(null, "Please select both a user and a route.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String userId = selectedUser.split(" - ")[0];
    String routeId = selectedRoute.split(" - ")[0];

    User user = business.getUserDirectory().findUserById(userId);
    Route route = business.getRouteDirectory().findRouteById(routeId);

    if (user != null && route != null) {
        route.setAssignedUser(user);
        user.addAssignedRoute(route); // Update the user's assigned routes
        JOptionPane.showMessageDialog(null, "User " + user.getName() + " successfully assigned to route " + route.getDescription(), "Assignment Successful", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "Failed to assign user to route. Check if user and route IDs are correct.", "Assignment Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnAssignRouteSetActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
                                           
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    Component[] components = userProcessContainer.getComponents();
    for (Component component : components) {
        if (component instanceof SupervisorDashboard) {
            SupervisorDashboard dashboard = (SupervisorDashboard) component;
            dashboard.populateDriverTruckTable();
        }
    }

    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRouteSet;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> comboRoute;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JLabel lblChooseUser;
    private javax.swing.JLabel lblRouteNo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
