/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Supervisor;

import Model.Business.Business;
import Model.Driver.Driver;
import Model.Driver.DriverDirectory;

import Model.Supervisor.Supervisor;
import Model.Supervisor.SupervisorDirectory;
import Model.Truck.Truck;
import UI.Dashboard.SupervisorDashboard;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class SupervisorAssignTruck extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Supervisor authenticatedSupervisor;
    private SupervisorDirectory supervisorDirectory;
    private Business business;
    private SupervisorDashboard dashboard;
    

    /**
     * Creates new form SupervisorAssignTruck
     */
    public SupervisorAssignTruck(JPanel userProcessContainer, Business business, Supervisor authenticatedSupervisor, SupervisorDirectory supervisorDirectory, SupervisorDashboard dashboard) {
       this.userProcessContainer = userProcessContainer;
    this.business = business;
    this.authenticatedSupervisor = authenticatedSupervisor;
    this.supervisorDirectory = supervisorDirectory;
    this.dashboard = dashboard;
    
    initComponents();
//    comboTruck = new JComboBox<>();
//    comboDriver = new JComboBox<>();
    initializeComboBoxes();  // Populate combo boxes after they have been initialized // Now call this after the combo boxes are initialized
      
    }
    
    private void assignTruckToDriver() {
        // logic to assign truck
        dashboard.populateDriverTruckTable();  // Refresh the table on dashboard after assignment
    }
    
     public void initializeComboBoxes() {
        comboTruck.removeAllItems();
        comboDriver.removeAllItems();

        business.getTruckDirectory().getAvailableTrucks().forEach(truck ->
            comboTruck.addItem(truck.getTruckId() + " - " + truck.getDescription())
        );

        DriverDirectory.getInstance().getAvailableDrivers().forEach(driver ->
            comboDriver.addItem(driver.getDriverId() + " - " + driver.getName())
        );
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseTruck = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblChooseDriver = new javax.swing.JLabel();
        btnset = new javax.swing.JButton();
        comboTruck = new javax.swing.JComboBox<>();
        comboDriver = new javax.swing.JComboBox<>();
        btnback = new javax.swing.JButton();

        setBackground(new java.awt.Color(54, 116, 99));

        lblChooseTruck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseTruck.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseTruck.setText("Choose Truck");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Assign Truck");

        lblChooseDriver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseDriver.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseDriver.setText("Choose Driver");

        btnset.setBackground(new java.awt.Color(181, 143, 120));
        btnset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnset.setForeground(new java.awt.Color(255, 255, 255));
        btnset.setText("Set");
        btnset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsetActionPerformed(evt);
            }
        });

        comboTruck.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnback.setBackground(new java.awt.Color(181, 143, 120));
        btnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("<<Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChooseDriver)
                    .addComponent(lblChooseTruck))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(btnset, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnback))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseDriver)
                    .addComponent(comboDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseTruck)
                    .addComponent(comboTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btnset)
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsetActionPerformed
        // TODO add your handling code here:
         if (comboTruck.getSelectedItem() == null || comboDriver.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Please select both a truck and a driver.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String selectedTruckInfo = comboTruck.getSelectedItem().toString();
    String selectedDriverInfo = comboDriver.getSelectedItem().toString();

    String truckId = selectedTruckInfo.split(" - ")[0];
    String driverId = selectedDriverInfo.split(" - ")[0];

    Truck assignedTruck = business.getTruckDirectory().findTruckById(truckId);
    Driver assignedDriver = DriverDirectory.getInstance().findDriverById(driverId);

    if (assignedTruck != null && assignedDriver != null) {
        assignedDriver.setAssignedTruck(assignedTruck);  // Make sure this method also updates the truck's driver
        JOptionPane.showMessageDialog(this, "Truck " + truckId + " assigned to driver " + assignedDriver.getName(), "Assignment Successful", JOptionPane.INFORMATION_MESSAGE);
        dashboard.populateDriverTruckTable();  // Refresh the dashboard table
    } else {
        JOptionPane.showMessageDialog(this, "Error in assigning truck to driver.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnsetActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        dashboard.populateDriverTruckTable();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnset;
    private javax.swing.JComboBox<String> comboDriver;
    private javax.swing.JComboBox<String> comboTruck;
    private javax.swing.JLabel lblChooseDriver;
    private javax.swing.JLabel lblChooseTruck;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
