/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Supervisor;

import Model.Business.Business;
import Model.Driver.Driver;
import Model.Supervisor.Supervisor;
import Model.Supervisor.SupervisorDirectory;
import Model.Truck.Truck;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author tawde
 */
public class SupervisorAssignTruck extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Supervisor authenticatedSupervisor;
    private SupervisorDirectory supervisorDirectory;
    private Business business;

    /**
     * Creates new form SupervisorAssignTruck
     */
    public SupervisorAssignTruck(JPanel userProcessContainer, Business business, Supervisor authenticatedSupervisor, SupervisorDirectory supervisorDirectory) {
         this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.authenticatedSupervisor = authenticatedSupervisor;
        this.supervisorDirectory = supervisorDirectory;
        initComponents();
        initializeComboBoxes();
      
    }
    
    public void initializeComboBoxes() {
    // Assuming you have methods getAvailableTrucks() and getAvailableDrivers()
    // that return lists of trucks and drivers.
    for (Truck truck : business.getTruckDirectory().getAvailableTrucks()) {
        comboTruck.addItem(truck.getTruckId() + " - " + truck.getDescription());
    }
    for (Driver driver : business.getDriverDirectory().getAvailableDrivers()) {
        comboDriver.addItem(driver.getDriverId() + " - " + driver.getName());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseTruck = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblChooseDriver = new javax.swing.JLabel();
        btnAssignTruck = new javax.swing.JButton();
        txtChooseDriver = new javax.swing.JTextField();
        txtChooseTruck = new javax.swing.JTextField();

        setBackground(new java.awt.Color(54, 116, 99));

        lblChooseTruck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseTruck.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseTruck.setText("Choose Truck");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Assign Truck");

        lblChooseDriver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseDriver.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseDriver.setText("Choose Driver");

        btnAssignTruck.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignTruck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAssignTruck.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignTruck.setText("Set");
        btnAssignTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTruckActionPerformed(evt);
            }
        });

        txtChooseDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChooseDriverActionPerformed(evt);
            }
        });

        txtChooseTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChooseTruckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChooseDriver)
                    .addComponent(lblChooseTruck))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChooseDriver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChooseTruck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChooseTruck)
                            .addComponent(txtChooseTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChooseDriver)
                        .addGap(12, 12, 12))
                    .addComponent(txtChooseDriver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(btnAssignTruck)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTruckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignTruckActionPerformed

    private void txtChooseDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChooseDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChooseDriverActionPerformed

    private void txtChooseTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChooseTruckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChooseTruckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignTruck;
    private javax.swing.JLabel lblChooseDriver;
    private javax.swing.JLabel lblChooseTruck;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtChooseDriver;
    private javax.swing.JTextField txtChooseTruck;
    // End of variables declaration//GEN-END:variables
}
