/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Supervisor;

/**
 *
 * @author tawde
 */
public class SupervisorAssignRoute extends javax.swing.JPanel {

    /**
     * Creates new form SupervisorAssignRoute
     */
    public SupervisorAssignRoute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssignRouteSet = new javax.swing.JButton();
        jTextFieldRouteID = new javax.swing.JTextField();
        lblRouteID = new javax.swing.JLabel();
        jTextFieldRouteNo = new javax.swing.JTextField();
        jTextFieldChooseTruck = new javax.swing.JTextField();
        lblChooseTruck = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblRouteNo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(54, 116, 99));

        btnAssignRouteSet.setBackground(new java.awt.Color(181, 143, 120));
        btnAssignRouteSet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAssignRouteSet.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRouteSet.setText("Set");
        btnAssignRouteSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRouteSetActionPerformed(evt);
            }
        });

        jTextFieldRouteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRouteIDActionPerformed(evt);
            }
        });

        lblRouteID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRouteID.setForeground(new java.awt.Color(255, 255, 255));
        lblRouteID.setText("Route ID");

        jTextFieldRouteNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRouteNoActionPerformed(evt);
            }
        });

        jTextFieldChooseTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChooseTruckActionPerformed(evt);
            }
        });

        lblChooseTruck.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChooseTruck.setForeground(new java.awt.Color(255, 255, 255));
        lblChooseTruck.setText("Choose Truck");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Assign Route");

        lblRouteNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRouteNo.setForeground(new java.awt.Color(255, 255, 255));
        lblRouteNo.setText("Route No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRouteID)
                    .addComponent(lblRouteNo)
                    .addComponent(lblChooseTruck))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRouteID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRouteNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldChooseTruck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssignRouteSet, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChooseTruck)
                            .addComponent(jTextFieldChooseTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRouteNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRouteID)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldRouteNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRouteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(btnAssignRouteSet)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignRouteSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRouteSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignRouteSetActionPerformed

    private void jTextFieldRouteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRouteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRouteIDActionPerformed

    private void jTextFieldRouteNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRouteNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRouteNoActionPerformed

    private void jTextFieldChooseTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChooseTruckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChooseTruckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRouteSet;
    private javax.swing.JTextField jTextFieldChooseTruck;
    private javax.swing.JTextField jTextFieldRouteID;
    private javax.swing.JTextField jTextFieldRouteNo;
    private javax.swing.JLabel lblChooseTruck;
    private javax.swing.JLabel lblRouteID;
    private javax.swing.JLabel lblRouteNo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
